#Makefile generated by amake
#On Wed Feb  1 19:43:06 2017
#To print amake help use 'amake --help'.
CC=arm-linux-gcc
CPPC=arm-linux-g++
LINK=arm-linux-g++
#CC=gcc
#CPPC=g++
#LINK=g++
SRCDIR=./src
OBJDIR=obj
FLAGS=-g -Wall -std=c++11 
LIBS=
OBJS=$(OBJDIR)/options.o $(OBJDIR)/main.o $(OBJDIR)/uinput.o $(OBJDIR)/events.o $(OBJDIR)/joypads.o $(OBJDIR)/log.o 
EXEC=rg351p-js2xbox
DATE=$(shell date +"%Y-%m-%d")

$(EXEC) : $(OBJS)
	$(LINK) $(OBJS) -o $(EXEC) $(FLAGS) $(LIBS)

$(OBJDIR)/options.o: src/options.cpp src/options.h $(OBJDIR)/__setup_obj_dir
	$(CPPC) $(FLAGS) ./src/options.cpp -c -o $@

$(OBJDIR)/main.o: src/main.cpp src/log.h src/options.h src/events.h src/uinput.h \
 src/joypads.h $(OBJDIR)/__setup_obj_dir
	$(CPPC) $(FLAGS) ./src/main.cpp -c -o $@

$(OBJDIR)/uinput.o: src/uinput.cpp src/uinput.h src/events.h src/joypads.h $(OBJDIR)/__setup_obj_dir
	$(CPPC) $(FLAGS) ./src/uinput.cpp -c -o $@

$(OBJDIR)/events.o: src/events.cpp src/events.h src/log.h src/options.h $(OBJDIR)/__setup_obj_dir
	$(CPPC) $(FLAGS) ./src/events.cpp -c -o $@

$(OBJDIR)/joypads.o: src/joypads.cpp src/joypads.h src/events.h $(OBJDIR)/__setup_obj_dir
	$(CPPC) $(FLAGS) ./src/joypads.cpp -c -o $@

$(OBJDIR)/log.o: src/log.cpp src/log.h src/options.h $(OBJDIR)/__setup_obj_dir
	$(CPPC) $(FLAGS) ./src/log.cpp -c -o $@

$(OBJDIR)/__setup_obj_dir :
	mkdir -p $(OBJDIR)
	touch $(OBJDIR)/__setup_obj_dir

.PHONY: clean bzip release

clean :
	rm -rf $(OBJDIR)/*.o
	rm -rf $(EXEC)

bzip :
	tar -cvf "$(DATE).$(EXEC).tar" $(SRCDIR)/* Makefile
	bzip2 "$(DATE).$(EXEC).tar"

release : FLAGS +=-O3 -D_RELEASE
release : $(EXEC)

